FORMAT: 1A
HOST: /security/login

# Author : Udayakumar Mathivanan
# Security API

Security API which allows signup using revature account. This API will allow a revature user get authenticated with the backend


### POST /security/login 

+ Request (application/json)

    + Headers

            
            Content-Length: 99
   
    + Body
    
            {
                "userName": "testuser1@revature.com",
                "password": "MkNvbXBsZXg="
            }

+ Response 201 (application/json)

    + Headers

            Accept-Language: en

    + Body

            {
                 "primaryLocation": "Reston-VA",
                 "statusCode" : 200,
                 "description" : "Authentication successful",
                 "currentSystemRole" : {"id" : 1,"code" : "SR000","description" : "Super Admin","name" : "Super Admin" },
                 "loginToken" : "570284df-caa6-460c-bc13-cbbdac6e8149"
            }
            
+ Response 401 (application/json)

    + Headers

              Accept-Language: en

    + Body

            {
            
                 "statusCode" : 401,
                 "description" :"UnAuthorized or Invalid Credentials
               
            }