FORMAT: 1A
HOST: /security/login

# Author : Udayakumar Mathivanan
# Security API

Security API which allows signup using revature account. This API will allow a revature user get authenticated with the backend


### POST /security/login 


+ Response 201 (application/json)

    + Headers

            Accept-Language: en

    + Body

            {
                 "primaryLocation": "Reston-VA",
                 "statusCode" : 200,
                 "description" :"Authentication successful"
                 "currentSystemRole" : {"id" : 1,"code" : "SR000","description" : "Super Admin","name" : "Super Admin" }
                 "loginToken" : "LOGIN_TOKEN"
            }
            
+ Response 401 (application/json)

    + Headers

              Accept-Language: en

    + Body

            {
            
                 "statusCode" : 401,
                 "description" :"UnAuthorized or Invalid Credentials
               
            }