FORMAT: 1A
HOST: /security/login

# Author : Udayakumar Mathivanan
# CoreData API

CoreData API contains multiple endpoints which enables core operations


### POST /security/login 

+ Request (application/json)

    + Headers

            Content-Length: 99
   
    + Body

            {
                "userName": "testuser1@revature.com",
                "password": "dsh27282j=="
            }
         
+ Response 201 (application/json)

    + Headers

            Accept-Language: en

    + Body

            {
                 "primaryLocation": "Reston-VA",
                 "statusCode" : 201,
                 "description" : "Authentication successful",
                 "currentSystemRole" : {"id" : 1,"code" : "SR000","description" : "Super Admin","name" : "Super Admin" },
                 "loginToken" : "570284df-caa6-460c-bc13-cbbdac6e8149"
            }
            
+ Response 401 (application/json)

    + Headers

              Accept-Language: en

    + Body

            {
            
                 "statusCode" : 401,
                 "description" :"UnAuthorized or Invalid Credentials
               
            }
            
### GET /coredata/location?type=training

+ Request (application/json)

    + Headers
        
            Authorization: Bearer "570284df-caa6-460c-bc13-cbbdac6e8149"


+ Response 200 (application/json)

    + Headers

            Accept-Language: en

    + Body

            {
             "statusCode" : 200,
             "description" : "Authentication successful",
             "alllocation": 
            [
    
              {
                "id": "LOC001",
                "state": "FL",
                "campus": "UTA",
                "building": "Other"
              },
              {
                "id": "LOC002",
                "state": "FL",
                "campus": "USF",
                "building": "NEC"
              },
              {
                "id": "LOC003",
                "state": "FL",
                "campus": "USF",
                "building": "BSN”
              },
              {
                "id": "LOC004",
                "state": "VA”,
                "campus": "Reston",
                "building": "Headquarters"
              },
              {
                "id": "LOC005",
                "state": "NY”,
                "campus": "New York",
                "building": "NY"
              },
              {
                "id": "LOC006",
                "state": "TX”,
                "campus": "Dallas",
                "building": "TX"
              },
              {
                "id": "LOC007",
                "state": "West Virginia",
                "campus": "Morgantown",
                "building": "Other"
              },
              {
                "id": "LOC008",
                "state": "West Virginia",
                "campus": "Morgantown",
                "building": "Other"
              }
            ]
            
            }
### GET /coredata/room?type=training

+ Request (application/json)

    + Headers
        
            Authorization: Bearer "570284df-caa6-460c-bc13-cbbdac6e8149"


+ Response 200 (application/json)

    + Headers

            Accept-Language: en

    + Body

            {
             "statusCode" : 200,
             "description" : "Authentication successful",
             "allcampus": 
             [
            
            
              {
                "id": "CA001",
                "campus": "FL-UTA"
                
              },
              {
                "id": "CA002",
                "campus": "FL-USF"
               
              },
              {
                "id": "CA003",
                "campus": "FL-BSN"
                
              },
              {
                "id": "CA004",
                "campus": "VA-Reston"
               
              },
              {
                "id": "CA005",
                "campus": "NY-New York"
              
              },
              {
                "id": "CA006",
                "campus": "TX-Dallas"
               
              }
              
            ],
            "allrooms": 
            [
            
            
              {
                "id": "FL-USF-RR001",
                "room": "107",
                "capacity": 48
                
              },
              {
                "id": "FL-USF-RR002",
                "room": "200",
                "capacity": 45
               
              },
              {
                "id": "FL-USF-RR003",
                "room": "300",
                "capacity": 62
                
              },
              {
                "id": "FL-USF-RR004",
                "room": "300A",
                "capacity": 64
               
              },
              {
                "id": "FL-BSN-RR001",
                "room": "117",
                "capacity": 65
              
              },
              {
                "id": "VA-RES-RR001",
                "room": "14",
                "capacity": 25
               
              }
              ,
              {
                "id": "VA-RES-RR002",
                "room": "15",
                "capacity": 30
               
              }
              ,
              {
                "id": "VA-RES-RR003",
                "room": "16",
                "capacity": 50
               
              }
              
            ]
            
            }
            
### GET /coredata/trainers

+ Request (application/json)

    + Headers
        
            Authorization: Bearer "570284df-caa6-460c-bc13-cbbdac6e8149"


+ Response 200 (application/json)

    + Headers

            Accept-Language: en

    + Body

            {
             "statusCode" : 200,
             "description" : "Authentication successful",
             "trainers": 
              [
                {
                  "id": "TR001",
                  "name": "Fred B",
                  "emailaddress": "fred@revature.com",
                  "primarylocation": "Tampa, FL",
                  "profilepicture": "NO_IMAGE",
                  "skills": [
                    "JAVA",
                    "Oracle",
                    "HTML,CSS,Javascript"
                  ]
                },
                {
                  "id": "TR002",
                  "name": "Nick E",
                  "emailaddress": "nicke@revature.com",
                  "primarylocation": "Reston, VA",
                  "profilepicture": "NO_IMAGE",
                  "skills": [
                    "JAVA",
                    "Full-Stack ",
                    "AWS"
                  ]
                },
                {
                  "id": "TR004",
                  "name": "August D",
                  "emailaddress": "augustd@revature.com",
                  "primarylocation": "Tampa, FL",
                  "profilepicture": "NO_IMAGE",
                  "skills": [
                    "Java",
                    "AWS"
                  ]
                },
                {
                  "id": "TR005",
                  "name": "Alex Milevich",
                  "emailaddress": "alexandra.milevich@revature.com",
                  "primarylocation": "Tampa, FL",
                  "profilepicture": "NO_IMAGE",
                  "skills": [
                    "Java",
                    "PEGA"
                  ]
                },
                {
                  "id": "TR006",
                  "name": "Trevin C",
                  "emailaddress": "trevinc@revature.com",
                  "primarylocation": "Tampa, FL",
                  "profilepicture": "NO_IMAGE",
                  "skills": [
                    "Java",
                    "FullStack"
                  ]
                },
                {
                  "id": "TR007",
                  "name": "Mitch G",
                  "emailaddress": "mitchg@revature.com",
                  "primarylocation": "Tampa,FL",
                  "profilepicture": "NO_IMAGE",
                  "skills": [
                    "Java",
                    "PEGA",
                    "FullStack"
                  ]
                },
                {
                  "id": "TR009",
                  "name": "Udayakumar Mathivanan",
                  "emailaddress": "uday.kumar@revature.com",
                  "primarylocation": "Reston,VA",
                  "profilepicture": "https://s3-ap-southeast-1.amazonaws.com/tv-prod/member/photo/4907992-large.jpg",
                  "skills": [
                    "AWS Cloud",
                    "Google Cloud",
                    "Windows Azure Cloud",
                    "Java",
                    ".NET",
                    "ASP.NET",
                    "Machine Learning",
                    "iOS",
                    "Android",
                    "Xamarin",
                    "Dynamics CRM"
                  ]
                }
              ]

            }